@echo off
echo 正在设置 GitHub Secrets...

REM 设置 FLY_API_TOKEN
gh secret set FLY_API_TOKEN --body "FlyV1 fm2_lJPECAAAAAAAEJufxBB+rzGO5VLC0UwvSbbAttMDwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOABWVaR8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDz+87+pSnweUo3SCUH/EudsBuEqfjMWsx2rIx+q7wPjzZfUUyLxMauUitUCbZYXwVSPmFLLtst4aWy6vNnETgeAm+T+gWkOyCuIsX9Jp4ECCW5bRZ4TXfX2G1J3LmJfBPz4uAbUTlpYadwQCXjtQ9zVknvDGlCjKI8Q4mZkHJ1LJhmwGhD6bP13z3CA2sQguOzxSXuBG43CXaYgmKBdZRuHtmxVaF2joTmIWREgKX4=,fm2_lJPETgeAm+T+gWkOyCuIsX9Jp4ECCW5bRZ4TXfX2G1J3LmJfBPz4uAbUTlpYadwQCXjtQ9zVknvDGlCjKI8Q4mZkHJ1LJhmwGhD6bP13z3CA2sQQhjZkwTjLdiYCX4nQC+K+X8O5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5pW58tzwAAAAElU71LF84AFLoCCpHOABS6AgzEEFJMOcOEQxOQJmiZYEotNVrEIP0b6ABIDLEJ/EmDi3lWBrv9/JLf0jvrnjMceNEYYD87"

REM 设置 PROXY_API_KEY
gh secret set PROXY_API_KEY --body "my-super-secret-password-123"

REM 设置 REFRESH_TOKEN (需要你提供)
set /p REFRESH_TOKEN="请输入你的 REFRESH_TOKEN: "
gh secret set REFRESH_TOKEN --body "%REFRESH_TOKEN%"

REM 设置 ADMIN_PASSWORD
gh secret set ADMIN_PASSWORD --body "Kiro@2025"

echo 所有 Secrets 设置完成！
pause